#!/usr/bin/env python3
name: quote_tool

channels:
  - conda-forge
  - defaults
  
dependencies:
  # Try to install everything via conda where possible,
  # makes for simpler and quicker installs
  - python=3.9.12
  - numpy
  - pandas
  - openpyxl
  - matplotlib
  - spacy=3.3.1
  - spacy-model-en_core_web_sm
  - nltk
  - ipywidgets=8.0.2
  - pip
  - pip:
      - pyexcelerate
      - atap_widgets
      - sphinx==5.1.1
      - sphinx-click==4.3.0
      - sphinx-rtd-theme==1.0.0
